apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-constraint
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
    defaultRequest:
      cpu: 100m
    min:
      cpu: 100m
    max:
      cpu: 200m
