apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["list","get","create","update"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
