apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongodb

