apiVersion: apps/v1
kind: Deployment
metadata:
  name: myyamlfiles
  labels:
    app: ubuntu
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      name: myyamlfiles
      labels:
        app: ubuntu
    spec:
      containers:
      - name: myyamlfiles
        image: docker.io/ahmedsayedtalib/myyamlfiles:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
      tolerations:
      - key: "color"
        operator: "Equal"
        value: "blue"
        effect: "NoSchedule"
      - key: "color"
        operator: "Equal"
        value: "green"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - node1
                - node2
---
apiVersion: v1
kind: Service
metadata:
  name: myyamlfiles-service
  labels:
    app: ubuntu
spec:
  selector:
    app: ubuntu
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32110
