apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi 
      tolerations:
      - key: color
        operator: Equal
        value: blue
        effect: NoSchedule
      - key: color
        operator: Equal
        value: green
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - node1
                - node2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ahmedsayed
