apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      name: odoo
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:17.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      tolerations:
      - key: color
        operator: Equal
        value: green
        effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                - large
                - xlarge
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  labels:
    app: odoo
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
  - name: odoo-http
    port: 8069
    targetPort: 8069
    nodePort: 31110
  - name: odoo-longpolling
    port: 8072
    targetPort: 8072
    nodePort: 31111
