apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      name: odoo
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 512Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                - large
                - xlarge
      tolerations:
      - key: "color"
        operator: "Equal"
        value: "green"
        effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
