apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - large
                      - xlarge
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "green"
          effect: "NoExecute"
      containers:
        - name: postgres
          image: postgres
          env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: posgtres-config
                key: POSTGRES_USER
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key:  POSTGRES_USER
          - name: POSTGRESS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: password
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
