apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: postgres-odoo
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: odoo-erp
    ports:
    - protocol: TCP
      port: 5432
